### ISSUE TITLE
Attribute Slicer/ Textfilter plugins not working - PowerBI Report Server

### ISSUE THREAD

**Issue by neogen19** [microsoft/PowerBI-visuals-AttributeSlicer#100]
Hello,

I am having issues with AttributeSlicer and Textfilter plugin. The visuals doesn’t perform any operation when a value is entered or clicked. 

Issue came up after updating PowerBI Report Server to October 2019 version.

It works fine in PowerBI desktop and issue happens only after publishing to RS. Any advice  is greatly appreciated as many of my reports are using these plugins. Not aware of any alternate plugin too.

**Comment by stopyoukid** [comment]
Hello,

I don't see PBIRS October 2019, the latest I do see is September 2019, as such I can't test it.

However, in the forums, I do see several threads talking about slicers not being able to filter in the September 2019 version.  

- https://community.powerbi.com/t5/Report-Server/Text-Visual-not-working-in-PBIRS-September/td-p/804487

- https://community.powerbi.com/t5/Report-Server/Hierarchy-Slicer-visual-not-working-after-September-2019-update/td-p/808025

and it looks like the PowerBI team released an update https://community.powerbi.com/t5/Report-Server/Hierarchy-Slicer-visual-not-working-after-September-2019-update/m-p/815244#M11832
which _should_ fix it.

So, I would say, if that isn't your issue, your best bet is to post on https://community.powerbi.com, the Power BI team continually monitors those forums for bugs.

**Comment by uve** [comment]
@neogen19, @stopyoukid, Report Server team published QFE for September version of PBIRS. This build includes the fix for Slicers. Please make sure that use installed the latest version:
Build: **15.0.1102.646** 
Date Published: **10/25/2019**
https://www.microsoft.com/en-us/download/details.aspx?id=57270

**Comment by neogen19** [comment]
Thank you all. I have updated the version now and plugins are stable in this version. 
Appreciate your help on this.
