### ISSUE TITLE
Error with the pbiviz

### ISSUE THREAD

**Issue by AntMassip** [Microsoft/PowerBI-visuals-AttributeSlicer#35]
Hello

When i tried to generate the pbiviz with the command yarn test I got this error :

![image](https://cloud.githubusercontent.com/assets/22083963/26145315/4ff804da-3aec-11e7-8ce1-8616ab627894.png)

It says '!' is not recognize as an internal command.

Did I miss something ?

**Comment by stopyoukid** [comment]
No, you did not miss anything. There was some code that was bash specific. We've merged in some changes into the `develop` branch, which should fix your build issues, could you please check out the `develop` branch, and try again?

**Comment by AntMassip** [comment]
It is all right.

Thank you.

**Comment by stopyoukid** [comment]
What do you mean by "hide values"?  If you are talking about the bars in the attribute slicer, then there is no way to hide them (besides not adding a field to the "Values" section).  There is something that comes close, is you can make the Bars smaller by changing the Display -> Value Width % setting in the formatting pane, but the minimum size is 10%.

**Comment by AntMassip** [comment]
Yes I am talking about the bars.
But it is no longer a problem.
Thank you, you're doing a nice job.

**Comment by stopyoukid** [comment]
Thank you very much
