### ISSUE TITLE
Brush selection does not support ability to select two or more selections while holding Control

### ISSUE THREAD

**Issue by mpiecyk** [Microsoft/PowerBI-visuals-AttributeSlicer#53]
Currently, brush selection clears out whatever was selected beforehand. It would be nice to be able to hold Control and make multiple selections.

**Comment by ericleigh007** [comment]
Also, if I might add something, brush selection combined with the need to auto-scroll based upon the selection direction stops selecting a bit after the scroll starts.  Overall, we need a way to make multiple contiguous selections, and multiple non-contiguous ones.

**Comment by ericleigh007** [comment]
As well, a ^A select all "standard" would be appreciated as well.
-thanks, and great work.
