### ISSUE TITLE
Counts in small bars are not visible

### ISSUE THREAD

**Issue by mpiecyk** [Microsoft/PowerBI-visuals-AttributeSlicer#54]
If the bars with the counts are 1px wide, the count value cannot be read by the user. It would be nice to have a setting that moves the counts to the right of the bar in a different color when they don't fit, so the count is visible there, for example.

**Comment by eric-kimbrel** [comment]
I am trying to figure out how this would work with multiple segments on the line.   I believe this request assumes  the data only has one segment, such that mousing over the row anywhere could simply show the value for that row.  With multiple segments in a row the user needs to mouse over the part of the bar they are interested in seeing.  This may only be one pixel wide and there may be many of them right against each other making it very difficult to accurately select the value you are looking for.

Currently if you mouse over the portion of the bar you are interested in you should see a browser tool tip that shows the segment and the value, so you can't see the value on the bar but you can see it in the tool tip if you are able to mouse over the segment.

If we can come up with an elegant solution that handles multiple segments then we can add this feature but its unclear what we can do right now.

**Comment by mpiecyk** [comment]
I didn't realize you could hover, that is helpful to see the value. However, here's a screenshot of my Power BI report with your Attribute Slicer showing that sometimes, the bar is 0px wide, so hovering is still not an option. (Of course, the value is not 0, or it wouldn't show up in your Attribute Slicer.) So, the users of my report have been asking if the Attribute Slicer could support making the number visible, as even though the number is small in relative value, they still care about it.

Whatever solution you come up with may not be ideal for all users, so I suggest making it a configurable setting.

My suggestion is to always make the count visible somewhere, even when the bar is 0px wide. Since the bar color and background color are often different, the "out of the bar" and "in the bar" font color would need to vary as well to be readable.

![image](https://user-images.githubusercontent.com/7647905/28231939-f25535e8-68a2-11e7-9940-acbe66e365a6.png)

**Comment by eric-kimbrel** [comment]
We are adding an option (Overflow value text) under display in the format pane.  This will allow the text for values to overflow the value bar to make them visible.   It should work well for the case presented above.

You may also want to use in conjunction with the "Always on Values" option.

**Comment by mpiecyk** [comment]
Excellent, thanks a lot! I will use that "Always on Values" option in addition to the new feature "Overflow value text" when the next package of this project is released.
