### ISSUE TITLE
Attribute Slicer working on PowerBI Desktop but stopped working when published to service

### ISSUE THREAD

**Issue by ChaChaChaChami** [Microsoft/PowerBI-visuals-AttributeSlicer#72]
Attribute Slicer working on PowerBI Desktop but stopped working when published to service. Doesn't filter any tables/charts on published assets. This is a recent development not sure if it's a problem with the Slicer or with the service (MSIT). Also escalated through MSIT.

**Comment by stopyoukid** [comment]
Thank you for the report, we will investigate

**Comment by Licantrop0** [comment]
also happening to me, I can share the pbxi

**Comment by nilavalagan** [comment]
I see the same issue happening to me. It works fine in Desktop app. I also realized that it is not working only for specific datasets.

**Comment by stopyoukid** [comment]
@nilavalagan Could you provide a small sample dataset that exhibits this issue?

**Comment by nilavalagan** [comment]
Removing and Re-Adding the attribute slicer helped.

**Comment by StepanPetr** [comment]
I have the same problem. I attach an example. I use PBI Desktop form repot server (January 2019) and i publish on Report server Version 1.4.6969.7395 (January 2019). Thank you
[Sample.zip](https://github.com/Microsoft/PowerBI-visuals-AttributeSlicer/files/2876280/Sample.zip)

**Comment by stopyoukid** [comment]
Going to close this issue, @StepanPetr I've moved your issue here #93, your issue is likely different than this one.

**Comment by antonang** [comment]
Attribute Slicer had stopped showing when published to web. It still shows in Power BI Desktop and in Power BI Service but when published to web, it is blank in the preview window and only shows the containwer without the items when published to web. This happened a day ago.
