### ISSUE TITLE
Can't add visual level filter for this Slicer

### ISSUE THREAD

**Issue by Licantrop0** [Microsoft/PowerBI-visuals-AttributeSlicer#73]
I need to exclude some values from the slicer that will throw off the visualization:

![image](https://user-images.githubusercontent.com/2388430/32855662-3c8cd3d6-c9f7-11e7-8a3d-cc96b7a9c2fa.png)
(in this case, I have to remove S_OK)

but it's impossible to add a Visual Level Filter.

**Comment by stopyoukid** [comment]
I'm sorry, unfortunately that is a limitation on slicers. A workaround, although crude, is to have another **hidden** slicer that **only** filters this one, and select the options from the hidden one that you want to display in this one.

**Comment by Licantrop0** [comment]
That's very bad, I hope Power BI team will fix this limitation...
I discovered [an idea](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/12545673-visual-level-filtering-in-slicers) that is asking exactly that.
 Anyway, thanks for the workaround, it's clunky but it works...
