### ISSUE TITLE
Format tab stopped displaying advanced options in November Update

### ISSUE THREAD

**Issue by Licantrop0** [Microsoft/PowerBI-visuals-AttributeSlicer#74]
With Power Bi v2.52.4921.682 64-bit, the advanced format options are gone, this is what I currently see:

![image](https://user-images.githubusercontent.com/2388430/33051673-ffa1fd66-ce1f-11e7-84cc-17d19db6a3f9.png)

**Comment by stopyoukid** [comment]
Thanks for the report, we will investigate.
