### ISSUE TITLE
VISUAL LEVEL FILTER DOES NOT ACCEPT ATTRIBUTES

### ISSUE THREAD

**Issue by MagicMads** [Microsoft/PowerBI-visuals-AttributeSlicer#78]
WHEN DRAGGING AN ATTRIBUTE TO THE VISLA LEVEL FILTER IT HIGHLIGHTS BUT DOES NOT ACCEPT THE ATTRIBUTE

**Comment by stopyoukid** [comment]
Thank you for your patience.  We were trying to move off of PBI's legacy API and onto their approved API, and wanted to see if doing that fixed this issue.  Unfortunately, it does not.  This seems to be a limitation of slicers/filtering visuals.  You can see this issue as well with the built in Slicer, it does not allow fields to be dragged into the "Visual Level Filter"
