### ISSUE TITLE
Attribute Slicer stops working when published to report server.

### ISSUE THREAD

**Issue by stopyoukid** [Microsoft/PowerBI-visuals-AttributeSlicer#93]
I have the same problem. I attach an example. I use PBI Desktop form repot server (January 2019) and i publish on Report server Version 1.4.6969.7395 (January 2019). Thank you
[Sample.zip](https://github.com/Microsoft/PowerBI-visuals-AttributeSlicer/files/2876280/Sample.zip)

_Originally posted by @StepanPetr in https://github.com/Microsoft/PowerBI-visuals-AttributeSlicer/issues/72#issuecomment-464773565_

**Comment by stopyoukid** [comment]
@StepanPetr I do not see an issue, is there something you are experiencing in particular that is broken.  I tried searching and filtering in Attribute Slicer and I do not see any issues.

I also used January 2019 Report Server and PowerBI Desktop.

Perhaps this was a hiccup in PowerBI?

**Comment by StepanPetr** [comment]
Thanks David. I found a solution. Problem was only in google chrome and cahced files. I cleared cached files in google chrome and problem is solved.

**Comment by stopyoukid** [comment]
Glad to hear that your issue was resolved. I'll remember that fix if an issue like this comes up again.
